# -*- coding: utf-8 -*-
"""Copia de CifradoImgRegla90R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158mlya6ojIn5kpUGk-JYxf1Crzaeerl_
"""

import numpy as np

def regla_90R(t0, t1):
    n = len(t0)
    t2 = np.zeros(n, dtype=np.uint8)
    for i in range(n):
        left = t1[i - 1] if i - 1 >= 0 else 0
        right = t1[i + 1] if i + 1 < n else 0
        center = t0[i]
        t2[i] = (left + right + center) % 2
    return t2

def cifrar_imagen_binaria(img_binaria, num_iteraciones):
    """
    Aplica cifrado de autómata celular por filas.
    img_binaria: matriz numpy 2D de 0s y 1s.
    num_iteraciones: número de veces que se aplicará la regla 90R.
    """
    img = img_binaria.copy()
    filas, cols = img.shape

    # Recorremos la imagen de 2 en 2 filas
    for i in range(0, filas - 1, 2):
        t0 = img[i]
        t1 = img[i+1]

        for _ in range(num_iteraciones):
            t2 = regla_90R(t0, t1)
            t0, t1 = t1, t2  # avanzar estados

        img[i] = t0
        img[i+1] = t1

    return img

def convert_rows_to_binary(img):
    rows = img.shape[0]
    binary_rows = []

    for r in range(rows):
        # para cada fila, convertimos cada pixel a 8 bits binarios y concatenamos
        bin_str_row = ''.join(format(pixel, '08b') for pixel in img[r])
        # convertimos la cadena de bits a lista de ints (0/1)
        bin_list = [int(bit) for bit in bin_str_row]
        binary_rows.append(bin_list)

    # convertimos la lista de listas a un np.array 2D
    return np.array(binary_rows, dtype=np.uint8)

def binary_to_pixel_array(binary_img):
    rows, total_bits = binary_img.shape
    # Cada pixel ocupa 8 bits
    num_pixels_per_row = total_bits // 8

    pixel_rows = []
    for r in range(rows):
        row_bits = binary_img[r]
        pixels = []
        for i in range(num_pixels_per_row):
            # Extraer 8 bits por pixel
            byte_bits = row_bits[i*8:(i+1)*8]
            # Convertir bits a string
            byte_str = ''.join(str(b) for b in byte_bits)
            # Convertir string binario a entero decimal
            pixel_val = int(byte_str, 2)
            pixels.append(pixel_val)
        pixel_rows.append(pixels)

    return np.array(pixel_rows, dtype=np.uint8)

from PIL import Image
import matplotlib.pyplot as plt

# Cargar imagen binarizada (matriz 0s y 1s)
img = Image.open("imagen.png").convert("L")
img_np = np.array(img)
binaria = convert_rows_to_binary(img_np)

# Aplicar cifrado con 5 iteraciones
encriptada = cifrar_imagen_binaria(binaria, num_iteraciones=100)

np.save('encriptada.npy', encriptada)
print("Array guardado como 'encriptada.npy'")

encriptada = binary_to_pixel_array(encriptada)

# Mostrar resultados
plt.subplot(1, 2, 1)
plt.imshow(img_np, cmap='gray')
plt.title("Original binaria")

plt.subplot(1, 2, 2)
plt.imshow(encriptada, cmap='gray')
plt.title("Cifrada con Regla 90R")
plt.show()

import numpy as np

def regla_90R_inversa(t1, t2):
    """
    Dada t1 y t2, obtiene t0 aplicando la regla inversa.
    """
    n = len(t1)
    t0 = np.zeros(n, dtype=np.uint8)
    for i in range(n):
        left = t1[i - 1] if i - 1 >= 0 else 0
        right = t1[i + 1] if i + 1 < n else 0
        future = t2[i]
        t0[i] = (left + right + future) % 2
    return t0

def descifrar_imagen_binaria(img_cifrada, num_iteraciones):
    """
    Descifra la imagen binaria cifrada con la Regla 90R.

    img_cifrada: numpy 2D con la imagen cifrada (0s y 1s)
    num_iteraciones: número de iteraciones que se usaron para cifrar

    Retorna la imagen descifrada.
    """
    img = img_cifrada.copy()
    filas, cols = img.shape

    for i in range(0, filas - 1, 2):
        # Estado en t+1 y t+2 al final del cifrado (últimas dos filas)
        t2 = img[i+1]
        t1 = img[i]

        # Iterar hacia atrás para recuperar t0
        for _ in range(num_iteraciones):
            t0 = regla_90R_inversa(t1, t2)
            t2, t1 = t1, t0  # retroceder estados

        img[i] = t1
        img[i+1] = t2

    return img

encriptada = np.load('salida01.npz')
encriptada_bin = convert_rows_to_binary(encriptada)
img_descifrada = descifrar_imagen_binaria(encriptada_bin, 100)

img_descifrada = binary_to_pixel_array(img_descifrada)

plt.subplot(1, 2, 1)
plt.imshow(encriptada, cmap='gray')
plt.title("Original binaria")

plt.subplot(1, 2, 2)
plt.imshow(img_descifrada, cmap='gray')
plt.title("Cifrada con Regla 90R")